# Generated by Django 6.0.1 on 2026-07-28 17:55

import portal.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionpaper",
            name="pdf",
            field=models.FileField(
                storage=portal.storage.SupabaseStorage(), upload_to="question_papers/"
            ),
        ),
    ]
